
$('#textarea1').val('New Text');
M.textareaAutoResize($('#textarea1'));
$('#textarea2').val('New Text');
M.textareaAutoResize($('#textarea2'));
$('#textarea3').val('New Text');
M.textareaAutoResize($('#textarea3'));
$('#textarea4').val('New Text');
M.textareaAutoResize($('#textarea4'));
$('#textarea5').val('New Text');
M.textareaAutoResize($('#textarea5'));
$('#textarea6').val('New Text');
M.textareaAutoResize($('#textarea6'));
$('#textarea7').val('New Text');
M.textareaAutoResize($('#textarea7'));
$('#textarea8').val('New Text');
M.textareaAutoResize($('#textarea8'));
$('#textarea9').val('New Text');
M.textareaAutoResize($('#textarea9'));
$('#textarea10').val('New Text');
M.textareaAutoResize($('#textarea10'));
$('#textarea11').val('New Text');
M.textareaAutoResize($('#textarea11'));
$('#textarea12').val('New Text');
M.textareaAutoResize($('#textarea12'));
$('#textarea13').val('New Text');
M.textareaAutoResize($('#textarea13'));
$('#textarea14').val('New Text');
M.textareaAutoResize($('#textarea14'));
$('#textarea15').val('New Text');
M.textareaAutoResize($('#textarea15'));